version: "3.8"
services:
  horsing-b-redis:
    image: redis
    container_name: horsing-b-redis
    restart: always
    env_file: .env
    ports:
      - "6480:${REDIS_PORT}"
  horsing-b-postgres:
    image: postgres:latest
    container_name: horsing-b-postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5433:${DATABASE_PORT}
  horsing-b-production:
    container_name: horsing-b-api-production
    build:
      target: production
      context: .
      args:
        - PORT=${NEST_PORT}
    ports:
      - 3002:${NEST_PORT}
  horsing-b-dev:
    container_name: horsing-b-api-dev
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: horsing-b-postgres
      DATABASE_PORT: ${DATABASE_PORT}
    build:
      target: dev
      context: .
      args:
        - PORT=${NEST_PORT}
    #entrypoint: ["npm", "run", "start:dev"]
    ports:
      - 3002:${NEST_PORT}
      - 9229:9229 #debuggin port
    # volumes:
    #   - .:/horsing-b-app
    #   - node_modules:/horsing-b-app/node_modules/
    command: npm run start:debug # override entry command
    depends_on:
      - horsing-b-postgres
      - horsing-b-redis
    links:
      - horsing-b-postgres
      - horsing-b-redis
# volumes:
#   node_modules: null
#   docker-nest-postgres: null