version: "3.8"
services:
  horsing-b-postgres:
    image: postgres:latest
    container_name: horsing-b-postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5433:${DATABASE_PORT}